"""SLMP4E Connect Python: SLMP 4E frame (binary) client library."""

from .client import (
    BlockReadResult,
    DeviceBlockResult,
    LabelArrayReadPoint,
    LabelArrayReadResult,
    LabelArrayWritePoint,
    LabelRandomReadResult,
    LabelRandomWritePoint,
    LongTimerResult,
    MonitorResult,
    RandomReadResult,
    SLMP4EClient,
    TypeNameInfo,
)
from .core import (
    DeviceRef,
    ExtensionSpec,
    PLCSeries,
    SLMPBoundaryBehaviorWarning,
    SLMPError,
    SLMPPracticalPathWarning,
    SLMPRequest,
    SLMPTarget,
    SLMPUnsupportedDeviceError,
    build_device_modification_flags,
    decode_4e_request,
    decode_4e_response,
    encode_4e_request,
    encode_extended_device_spec,
    encode_extension_spec,
    parse_device,
)

__version__ = "0.1.2"

__all__ = [
    "BlockReadResult",
    "DeviceBlockResult",
    "DeviceRef",
    "ExtensionSpec",
    "LabelArrayReadPoint",
    "LabelArrayReadResult",
    "LabelArrayWritePoint",
    "LabelRandomReadResult",
    "LabelRandomWritePoint",
    "LongTimerResult",
    "MonitorResult",
    "PLCSeries",
    "RandomReadResult",
    "SLMPBoundaryBehaviorWarning",
    "SLMP4EClient",
    "SLMPError",
    "SLMPPracticalPathWarning",
    "SLMPRequest",
    "SLMPUnsupportedDeviceError",
    "SLMPTarget",
    "TypeNameInfo",
    "__version__",
    "build_device_modification_flags",
    "decode_4e_request",
    "decode_4e_response",
    "encode_4e_request",
    "encode_extended_device_spec",
    "encode_extension_spec",
    "parse_device",
]
